name: Deploying React App to EC2

on:
  push:
    branches:
      - main  # there was a space missing before "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.2.0

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
          sudo systemctl restart nginx
          echo "✅ Asad, all done!"
