name: deploying react app to ec2
on:
  push:
    branches:
      -main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
     - name: checkout code
       uses: actions/checkout@v4.2.2
     - name: install nodejs
       uses: actions/setup-node@v4.4.0
       with:
         node-version: 18.2.0
     - name: dependencies 
       run: npm install
     - name: building app here
       run: npm run build
     - name: deploying to nginx
       run: |
         sudo rm -rf /var/www/html/*
         sudo cp -r build/* /var/www/html/
         sudo systemctl restart nginx
         echo "asad all done"
         
